// This file is generated by Astro DB
declare module 'astro:db' {
	export const Project: import("@astrojs/db/runtime").Table<
		"Project",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Project","primaryKey":true}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Project","primaryKey":false,"optional":false}},"excerpt":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"excerpt","collection":"Project","primaryKey":false,"optional":false}},"image":{"type":"json","schema":{"optional":true,"unique":false,"deprecated":false,"name":"image","collection":"Project","default":{"src":"","alt":""}}},"testimonial":{"type":"json","schema":{"optional":true,"unique":false,"deprecated":false,"name":"testimonial","collection":"Project","default":{"text":"","author":"","position":""}}}}
	>;
	export const Blog: import("@astrojs/db/runtime").Table<
		"Blog",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Blog","primaryKey":true}},"title":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"title","collection":"Blog","primaryKey":false,"optional":false}},"excerpt":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"excerpt","collection":"Blog","primaryKey":false,"optional":false}},"image":{"type":"json","schema":{"optional":true,"unique":false,"deprecated":false,"name":"image","collection":"Blog","default":{"src":"","alt":""}}},"content":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"content","collection":"Blog","primaryKey":false,"optional":false}},"author":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"author","collection":"Blog","primaryKey":false,"optional":false,"references":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Author","primaryKey":false,"optional":false}}}},"date":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"date","collection":"Blog"}}}
	>;
	export const Author: import("@astrojs/db/runtime").Table<
		"Author",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Author","primaryKey":true}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Author","primaryKey":false,"optional":false}},"email":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"email","collection":"Author","primaryKey":false,"optional":false}},"bio":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"bio","collection":"Author","primaryKey":false,"optional":true}}}
	>;
	export const Testimonial: import("@astrojs/db/runtime").Table<
		"Testimonial",
		{"text":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"text","collection":"Testimonial","primaryKey":false,"optional":false}},"author":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"author","collection":"Testimonial","primaryKey":false,"optional":false}},"position":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"position","collection":"Testimonial","primaryKey":false,"optional":false}}}
	>;
}
